controller:

  hostPort:
    enabled: true

  metrics:
    enabled: true

    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  
  nodeSelector:
    ingress-ready: "true"

  service:
    type: NodePort
  
  tolerations:
   - key: "node-role.kubernetes.io/control-plane"
     operator: "Exists"
     effect: "NoSchedule"
