apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: kube-proxy2
  name: kube-proxy2
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-proxy2
  template:
    metadata:
      labels:
        app: kube-proxy2
    spec:
      nodeSelector:
        kube-proxy: v2
      serviceAccountName: kube-proxy
      hostNetwork: true
      containers:
      - image: mcluseau/kube-proxy2
        name: kube-proxy2
        volumeMounts:
        - name: empty
          mountPath: /k8s
        args:
        - --listen
        - unix:///k8s/proxy.sock
      - image: mcluseau/kube-proxy2
        name: kube-proxy-nftables
        securityContext:
          capabilities:
           add:
           - NET_ADMIN
        volumeMounts:
        - name: empty
          mountPath: /k8s
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        command:
        - kube-proxy-nftables
        - --target
        - unix:///k8s/proxy.sock
        #- --v=2
        #- --dry-run
      volumes:
      - name: empty
        emptyDir: {}
      - name: modules
        hostPath:
          path: /lib/modules
