name: Unit Tests Build

on:
  push:
    branches:
      - main
      - master
      - github_actions # TODO delete this if ever merged to master/main
  pull_request:
    branches:
      - main
      - master
      - github_actions # TODO delete this if ever merged to master/main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.3'

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

  build_tests:
    name: build unit tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: Build unit tests
      run: ./hack/test_unit.sh

