name: Code format verify

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  gofmt:
    name: Run gofmt verify
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.work

      - name: Install dependencies
        run: |
          go version
          go install golang.org/x/lint/golint@latest

      - name: checkout
        uses: actions/checkout@v3

      - name: run gofmt tests
        run: ./hack/verify-gofmt.sh
